### ISSUE TITLE
[Feat]: Adding for Multi-language Support in Ticketify

### ISSUE THREAD

**Issue by IkkiOcean** [maniyaom/Movie-Ticket-Booking#201]
### Feature Description

We need to integrate Google Translator into the Rentalog web application to allow users to translate all pages into multiple languages.

### Description:
This will enhance the user experience for non-English-speaking users by providing them with an accessible interface in their preferred language.

### Tasks:

	1.	Investigate the Google Translator API or other suitable translation tools.
	2.	Integrate the translator into the main layout of the application.
	3.	Ensure translation is available for all pages
	4.	Add a language selector dropdown to the header/footer for easy language switching.
	5.	Test translations to ensure proper formatting and layout across all languages.

### Acceptance Criteria:

	•	Users should be able to translate any page to their selected language using the Google Translator integration.
	•	The layout and styling of pages should not break when the content is translated.
	•	The language selector should be accessible and functional on all pages.

### Program: GSSOC-ext and hacktoberfest
** Please add LEVEL 3 to the issue**

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@IkkiOcean As far as I know, The Google Translator API isn't freely available. If you have any alternatives in mind, please let me know.

**Comment by IkkiOcean** [comment]
> @IkkiOcean As far as I know, The Google Translator API isn't freely available. If you have any alternatives in mind, please let me know.
@maniyaom No we wont need API key for this feature. I know a way around in react js to do it. assign this to me. It will be a selection button near navbar to help choose users their preferred language

**Comment by maniyaom** [comment]
@IkkiOcean can you do it for aboutus.js first. Then I will review it.

**Comment by maniyaom** [comment]
@IkkiOcean Just send me updated file for aboutus.js after completion of language support.

**Comment by IkkiOcean** [comment]
> @IkkiOcean Just send me updated file in personal for aboutus.js after completion of language support.
> 
> Discord: ommaniya_53106

- I wont be converting each page to some language. my plan is to create a component to choose multiple language from , and the selected language will be implemented on the whole application.
- so instead sending it to you on discord just for aboutus.js, what if I implement the feature on your application, share you the screenshot  and you decide whether you like it or not. is that good?

**Comment by Khizarshah01** [comment]
@IkkiOcean go ahead I assigned you this issue
