### ISSUE TITLE
[Feat]: Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by itshivams** [maniyaom/Movie-Ticket-Booking#436]
### Feature Description

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

### Provide a detailed description of the feature

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

and have to add sitemap.xml and robots file for search engine to crawl our site.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)
